name: ov_analysis

dependencies:
  - python=3.6
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - flake8
  - matplotlib
  - jupyter
  - seaborn
  - pip
  - yaml
  - pip:
    - pysftp 
    - Py-BOBYQA
    - DFO-LS
    - mpi4py
    - PyPDF2
    - jupyterlab
- pygraphviz
