name: dev_norpy

channels:
  - conda
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - pandas
  - statsmodels
  - pytest
  - pytest-xdist
  - scipy
  - flake8
  - jupyterlab
  - pip:
- oyaml
